# Site settings
title: "Ewan Panter | Working Notes"
description: "A personal blog I will probably fail to update."
baseurl: ""
url: "https://ewanpanter.github.io"

# Theme
remote_theme: chesterhow/tale
excerpt_separator: "<!--more-->"

# About me
author:
  name: "Ewan Panter"
  url: "https://uk.linkedin.com/in/ewan-panter-1a1a733"

# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title
timezone: Europe/London #yes it's raining

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Markdown
kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Files
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
